# Generated by Django 5.0 on 2024-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/', verbose_name='Фото')),
                ('title', models.CharField(max_length=150, verbose_name='Название формы')),
                ('Price', models.IntegerField(blank=True, verbose_name='Цена')),
            ],
        ),
    ]
